
package org.Spotify.JFrame;

import org.Spotify.GlobalData.ArrayData;
import java.util.UUID;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import org.Spotify.Models.Person;
import org.Spotify.Models.User;
import org.Spotify.Services.PersonService;


public class JFRegistryArtis extends javax.swing.JFrame {

    private Index index;
    
    public JFRegistryArtis() {
        initComponents();
    }
    
    private void newPersonRegistry(){
        PersonService personService = new PersonService();
        String id = UUID.randomUUID().toString();
        //validation Second name and Second lastname
        
        String secondName = jTextSecondName.getText().equals("Second name") || jTextSecondName.getText().isEmpty() ? null : jTextSecondName.getText();
        String secondLastName = jTextSecondLastName.getText().equals("Second lastname") || jTextSecondLastName.getText().isEmpty() ? null : jTextSecondLastName.getText();
        
        Person newPerson = new Person(id,jTextFirstName.getText(), secondName, jTextFirtsLastName.getText(), secondLastName, jTextEmail.getText());
        personService.addPerson(newPerson);
        ArrayData.personas.add(newPerson);
        ArrayData.artistas.add(new User(id));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelRegistry3 = new javax.swing.JLabel();
        jTextSecondLastName = new javax.swing.JTextField();
        jLabelRegistry6 = new javax.swing.JLabel();
        jTextEmail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButtonCreateUser = new javax.swing.JButton();
        jLabelRegistry1 = new javax.swing.JLabel();
        jButtonReturnLogin = new javax.swing.JButton();
        jTextFirstName = new javax.swing.JTextField();
        jLabelRegistry2 = new javax.swing.JLabel();
        jTextSecondName = new javax.swing.JTextField();
        jLabelRegistry4 = new javax.swing.JLabel();
        jTextFirtsLastName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelRegistry3.setFont(new java.awt.Font("Noto Sans CJK SC", 1, 14)); // NOI18N
        jLabelRegistry3.setText("Second lastname");

        jTextSecondLastName.setText("Second lastname");
        jTextSecondLastName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextSecondLastNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextSecondLastNameFocusLost(evt);
            }
        });

        jLabelRegistry6.setFont(new java.awt.Font("Noto Sans CJK SC", 1, 14)); // NOI18N
        jLabelRegistry6.setText("Email");

        jTextEmail.setText("user@domain.com");
        jTextEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextEmailFocusLost(evt);
            }
        });
        jTextEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextEmailActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Register Artist without user");
        jLabel1.setToolTipText("");

        jButtonCreateUser.setBackground(new java.awt.Color(0, 153, 0));
        jButtonCreateUser.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCreateUser.setText("Create Person");
        jButtonCreateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateUserActionPerformed(evt);
            }
        });

        jLabelRegistry1.setFont(new java.awt.Font("Noto Sans CJK SC", 1, 14)); // NOI18N
        jLabelRegistry1.setText("First name");

        jButtonReturnLogin.setBackground(new java.awt.Color(255, 51, 51));
        jButtonReturnLogin.setForeground(new java.awt.Color(255, 255, 255));
        jButtonReturnLogin.setText("Cancel");
        jButtonReturnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReturnLoginActionPerformed(evt);
            }
        });

        jTextFirstName.setText("First name");
        jTextFirstName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFirstNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFirstNameFocusLost(evt);
            }
        });
        jTextFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFirstNameActionPerformed(evt);
            }
        });

        jLabelRegistry2.setFont(new java.awt.Font("Noto Sans CJK SC", 1, 14)); // NOI18N
        jLabelRegistry2.setText("Second name");

        jTextSecondName.setText("Second name");
        jTextSecondName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextSecondNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextSecondNameFocusLost(evt);
            }
        });

        jLabelRegistry4.setFont(new java.awt.Font("Noto Sans CJK SC", 1, 14)); // NOI18N
        jLabelRegistry4.setText("Firts lastname");

        jTextFirtsLastName.setText("Firts lastname");
        jTextFirtsLastName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFirtsLastNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFirtsLastNameFocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelRegistry6)
                        .addComponent(jTextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelRegistry1)
                                .addComponent(jLabelRegistry4)
                                .addComponent(jTextFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFirtsLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(60, 60, 60)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextSecondName, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelRegistry3)
                                .addComponent(jLabelRegistry2)
                                .addComponent(jTextSecondLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(29, 29, 29)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonCreateUser)
                        .addGap(118, 118, 118)
                        .addComponent(jButtonReturnLogin)))
                .addGap(82, 82, 82))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRegistry1)
                    .addComponent(jLabelRegistry2))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextSecondName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRegistry4)
                    .addComponent(jLabelRegistry3))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFirtsLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextSecondLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabelRegistry6)
                .addGap(8, 8, 8)
                .addComponent(jTextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCreateUser)
                    .addComponent(jButtonReturnLogin))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextSecondLastNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextSecondLastNameFocusGained
        if(jTextSecondLastName.getText().equals("Second lastname")){
            jTextSecondLastName.setText(null);
            jTextSecondLastName.requestFocus();
            index.removePlaceHolderStyle(jTextSecondLastName);
        }
    }//GEN-LAST:event_jTextSecondLastNameFocusGained

    private void jTextSecondLastNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextSecondLastNameFocusLost
        if(jTextSecondLastName.getText().length()==0){
            jTextSecondLastName.setText("Second lastname");
            index.addPlaceHolderStyle(jTextSecondLastName);
        }
    }//GEN-LAST:event_jTextSecondLastNameFocusLost

    private void jTextEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextEmailFocusGained
        if(jTextEmail.getText().equals("user@domain.com")){
            jTextEmail.setText(null);
            jTextEmail.requestFocus();
            index.removePlaceHolderStyle(jTextEmail);
        }
    }//GEN-LAST:event_jTextEmailFocusGained

    private void jTextEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextEmailFocusLost
        if(jTextEmail.getText().length()==0){
            jTextEmail.setText("user@domain.com");
            index.addPlaceHolderStyle(jTextEmail);
        }
    }//GEN-LAST:event_jTextEmailFocusLost

    private void jTextEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextEmailActionPerformed

    private void jButtonCreateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateUserActionPerformed
        if(confirmData()){
            newPersonRegistry();
            JOptionPane.showMessageDialog(null, "Successful registration - Try registering again");
            JFHome open = new JFHome();
            open.setVisible(true);
            open.setLocationRelativeTo(null);
            open.setResizable(false);
            this.setVisible(false);
        }
        else{
            JOptionPane.showMessageDialog(null, "Failure to register");
        }
    }//GEN-LAST:event_jButtonCreateUserActionPerformed

    private void jButtonReturnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReturnLoginActionPerformed

        JFHome open = new JFHome();
        open.setVisible(true);
        open.setLocationRelativeTo(null);
        open.setResizable(false);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonReturnLoginActionPerformed

    private void jTextFirstNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFirstNameFocusGained
        if(jTextFirstName.getText().equals("First name")){
            jTextFirstName.setText(null);
            jTextFirstName.requestFocus();
            index.removePlaceHolderStyle(jTextFirstName);
        }
    }//GEN-LAST:event_jTextFirstNameFocusGained

    private void jTextFirstNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFirstNameFocusLost
        if(jTextFirstName.getText().length()==0){
            index.addPlaceHolderStyle(jTextFirstName);
            jTextFirstName.setText("First name");
        }
    }//GEN-LAST:event_jTextFirstNameFocusLost

    private void jTextFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFirstNameActionPerformed

    private void jTextSecondNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextSecondNameFocusGained
        if(jTextSecondName.getText().equals("Second name")){
            jTextSecondName.setText(null);
            jTextSecondName.requestFocus();
            index.removePlaceHolderStyle(jTextSecondName);
        }
    }//GEN-LAST:event_jTextSecondNameFocusGained

    private void jTextSecondNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextSecondNameFocusLost
        if(jTextSecondName.getText().length()==0){
            jTextSecondName.setText("Second name");
            index.addPlaceHolderStyle(jTextSecondName);
        }
    }//GEN-LAST:event_jTextSecondNameFocusLost

    private void jTextFirtsLastNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFirtsLastNameFocusGained
        if(jTextFirtsLastName.getText().equals("Firts lastname")){
            jTextFirtsLastName.setText(null);
            jTextFirtsLastName.requestFocus();
            index.removePlaceHolderStyle(jTextFirtsLastName);
        }
    }//GEN-LAST:event_jTextFirtsLastNameFocusGained

    private void jTextFirtsLastNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFirtsLastNameFocusLost
        if(jTextFirtsLastName.getText().length()==0){
            jTextFirtsLastName.setText("Firts lastname");
            index.addPlaceHolderStyle(jTextFirtsLastName);
        }
    }//GEN-LAST:event_jTextFirtsLastNameFocusLost

    private boolean confirmData(){
        if(jTextFirstName.getText().equals("First name") || jTextFirstName.getText().length()==0
                && jTextFirtsLastName.getText().length()==0 || jTextFirtsLastName.getText().equals("Firts lastname")
                && jTextEmail.getText().length()==0 || jTextEmail.getText().equals("user@domain.com")){
            JOptionPane.showMessageDialog(null, "Tienes campos vacios en el registro.");
            return false;
        }
        else{
            return true;
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCreateUser;
    private javax.swing.JButton jButtonReturnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelRegistry1;
    private javax.swing.JLabel jLabelRegistry2;
    private javax.swing.JLabel jLabelRegistry3;
    private javax.swing.JLabel jLabelRegistry4;
    private javax.swing.JLabel jLabelRegistry6;
    private javax.swing.JTextField jTextEmail;
    private javax.swing.JTextField jTextFirstName;
    private javax.swing.JTextField jTextFirtsLastName;
    private javax.swing.JTextField jTextSecondLastName;
    private javax.swing.JTextField jTextSecondName;
    // End of variables declaration//GEN-END:variables
}
