/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.Spotify.JFrame;

import javax.swing.JOptionPane;
import org.Spotify.Controllers.SongController;

/**
 *
 * @author Yo
 */
public class JPCrudSong extends javax.swing.JPanel {

    private JFHome home;
    SongController songCon = new SongController();
    
    public JPCrudSong(JFHome home) {
        initComponents();
        this.home = home;
    }
    
    public String getIdSong(){
        String songName = jTFSongName.getText();
        String idSong = songCon.getIdSong(songName);
        
        return idSong;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBSongAdd = new javax.swing.JButton();
        jBSongUpdate = new javax.swing.JButton();
        jBSongRead = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTFSongName = new javax.swing.JTextField();

        jBSongAdd.setText("Add Song");
        jBSongAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSongAddActionPerformed(evt);
            }
        });

        jBSongUpdate.setText("Update Song");
        jBSongUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSongUpdateActionPerformed(evt);
            }
        });

        jBSongRead.setText("Read Song");

        jLabel1.setText("Enter the name of the song to Up. or Re:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTFSongName)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jBSongAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBSongRead, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBSongUpdate))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jBSongAdd)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jTFSongName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jBSongUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jBSongRead)
                .addGap(27, 27, 27))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBSongAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSongAddActionPerformed
        String idSong = getIdSong();
        
        if (idSong == null){
            JOptionPane.showMessageDialog(this, "This Song isn't registered in the DB");
            return;
        }
        
        JFSong open = new JFSong(false, idSong);
        open.setVisible(true);
    }//GEN-LAST:event_jBSongAddActionPerformed

    private void jBSongUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSongUpdateActionPerformed
        String idSong = getIdSong();
        
        if (idSong == null){
            JOptionPane.showMessageDialog(this, "This Song isn't registered in the DB");
            return;
        }
        
        JFSong open = new JFSong(true, idSong);
        open.setVisible(true);
    }//GEN-LAST:event_jBSongUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBSongAdd;
    private javax.swing.JButton jBSongRead;
    private javax.swing.JButton jBSongUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTFSongName;
    // End of variables declaration//GEN-END:variables
}
