/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.Spotify.JFrame;

import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import org.Spotify.Models.User;
import org.Spotify.Services.UserService;

/**
 *
 * @author pipejfdv
 */
public class JPLoginOfIndex extends javax.swing.JPanel {
    private static String idUserLogin;
    private Index index;
            
    public JPLoginOfIndex(Index index) {
        initComponents();
        this.index = index;
        index.addPlaceHolderStyle(txtUser);
        index.addPlaceHolderStyle(jPasswordUser);
    }
    
    private void singIn() {
        UserService userService = new UserService();
        User credentials = userService.singInDB(txtUser.getText());
        if(credentials.getNickname().equals(txtUser.getText())
                && credentials.getPassword().equals(jPasswordUser.getText())){
            idUserLogin = credentials.getIdUser();
            JFHome home = new JFHome();
            home.setVisible(true);
            home.setLocationRelativeTo(null);
            home.setSize(650, 450);
            home.setResizable(false);
            index.setVisible(false);
        }
        else{
            JOptionPane.showMessageDialog(null, "credenciales incorrectas");
        }
    }

    public static String getIdUserLogin() {
        return idUserLogin;
    }

    public static void setIdUserLogin(String idUserLogin) {
        JPLoginOfIndex.idUserLogin = idUserLogin;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPasswordUser = new javax.swing.JPasswordField();
        jButtonSingIn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButtonRegistry = new javax.swing.JButton();
        backgroundImg = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Noto Sans CJK SC", 1, 18)); // NOI18N
        jLabel1.setText("Welcome to temu's Spotify");

        jLabel2.setFont(new java.awt.Font("Noto Sans CJK SC", 1, 14)); // NOI18N
        jLabel2.setText("User");

        txtUser.setFont(new java.awt.Font("Noto Sans CJK SC", 1, 12)); // NOI18N
        txtUser.setText("Nickname");
        txtUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUserFocusLost(evt);
            }
        });
        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Noto Sans CJK SC", 1, 14)); // NOI18N
        jLabel3.setText("Password");

        jPasswordUser.setFont(new java.awt.Font("Noto Sans CJK SC", 1, 12)); // NOI18N
        jPasswordUser.setText("password");
        jPasswordUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordUserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordUserFocusLost(evt);
            }
        });
        jPasswordUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordUserActionPerformed(evt);
            }
        });

        jButtonSingIn.setBackground(new java.awt.Color(0, 153, 0));
        jButtonSingIn.setFont(new java.awt.Font("Noto Sans CJK SC", 1, 12)); // NOI18N
        jButtonSingIn.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSingIn.setText("Sign in");
        jButtonSingIn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSingIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSingInActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Noto Sans CJK SC", 1, 12)); // NOI18N
        jLabel4.setText("Don't you have and account?");

        jButtonRegistry.setBackground(new java.awt.Color(0, 153, 0));
        jButtonRegistry.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRegistry.setText("¡Click here!");
        jButtonRegistry.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRegistry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistryActionPerformed(evt);
            }
        });

        backgroundImg.setIcon(new javax.swing.ImageIcon("/home/pipejfdv/Desktop/programs/DeskSpotifyMaven/src/main/java/org/Spotify/Views/Img/backgroundIndex.jpg")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(backgroundImg, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addComponent(txtUser)
                        .addComponent(jPasswordUser)
                        .addComponent(jButtonSingIn, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jButtonRegistry))
                .addGap(57, 57, 57))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPasswordUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonSingIn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRegistry)
                .addContainerGap(112, Short.MAX_VALUE))
            .addComponent(backgroundImg, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserFocusGained
        if(txtUser.getText().equals("Nickname")){
            txtUser.setText(null);
            txtUser.requestFocus();
            //remove placeholder
            index.removePlaceHolderStyle(txtUser);
        }
    }//GEN-LAST:event_txtUserFocusGained

    private void txtUserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserFocusLost
        if(txtUser.getText().length()==0){
            index.addPlaceHolderStyle(txtUser);
            txtUser.setText("Nickname");
        }
    }//GEN-LAST:event_txtUserFocusLost

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserActionPerformed

    private void jPasswordUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordUserFocusGained
        if(jPasswordUser.getText().equals("password")){
            jPasswordUser.setText(null);
            jPasswordUser.requestFocus();
            jPasswordUser.setEchoChar('o');
            index.removePlaceHolderStyle(jPasswordUser);
        }
    }//GEN-LAST:event_jPasswordUserFocusGained

    private void jPasswordUserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordUserFocusLost
        if(jPasswordUser.getText().length()==0){
            index.addPlaceHolderStyle(jPasswordUser);
            jPasswordUser.setText("password");
            jPasswordUser.setEchoChar('\u0000');
        }
    }//GEN-LAST:event_jPasswordUserFocusLost

    private void jPasswordUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordUserActionPerformed

    private void jButtonRegistryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistryActionPerformed
        JPNewRegistryOfIndex newRegistry = new JPNewRegistryOfIndex(this.index);
        index.changeContentNewRegistry(newRegistry);
    }//GEN-LAST:event_jButtonRegistryActionPerformed

    private void jButtonSingInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSingInActionPerformed
        if(txtUser.getText().equals("Nickname")
                || jPasswordUser.getText().equals("password")){
            JOptionPane.showMessageDialog(null, "No has ingresado credenciales.");
        }
        else{
            singIn();
        }
    }//GEN-LAST:event_jButtonSingInActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundImg;
    private javax.swing.JButton jButtonRegistry;
    private javax.swing.JButton jButtonSingIn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordUser;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
