package org.Spotify.JFrame;

import java.awt.Color;
import java.util.UUID;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import org.Spotify.Controllers.RolController;
import org.Spotify.Models.Person;
import org.Spotify.Models.Rol;
import org.Spotify.Models.User;
import org.Spotify.Services.PersonService;
import org.Spotify.Services.RolService;
import org.Spotify.Services.UserService;

public class JPNewRegistryOfIndex extends javax.swing.JPanel {

    private Index index;
    public boolean rolActive = false;
    public JPNewRegistryOfIndex(Index index) {
        initComponents();
        this.index = index;
        index.addPlaceHolderStyle(jTextFirstName);
        index.addPlaceHolderStyle(jTextSecondName);
        index.addPlaceHolderStyle(jTextFirtsLastName);
        index.addPlaceHolderStyle(jTextSecondLastName);
        index.addPlaceHolderStyle(jTextEmail);
        index.addPlaceHolderStyle(jTextNickname);
        index.addPlaceHolderStyle(jPasswordUser);
        index.addPlaceHolderStyle(jPasswordConfirmPassword);
    }
    
    private Rol activeRol(boolean rolAcive){
        RolController rol = new RolController(new RolService());
        if(rolAcive){
            jTArtis.setBackground(new Color(160, 57, 67));
            return rol.readRol("Artist");
        }
        else{
            return rol.readRol("User");
        }
    }
    
    private void newUserRegistry(){
        UserService userService = new UserService();
        PersonService personService = new PersonService();
        String id = UUID.randomUUID().toString();
        //validation Second name and Second lastname
        
        String secondName = jTextSecondName.getText().equals("Second name") || jTextSecondName.getText().isEmpty() ? null : jTextSecondName.getText();
        String secondLastName = jTextSecondLastName.getText().equals("Second lastname") || jTextSecondLastName.getText().isEmpty() ? null : jTextSecondLastName.getText();
        
        Person newPerson = new Person(id,jTextFirstName.getText(), secondName, jTextFirtsLastName.getText(), secondLastName, jTextEmail.getText());
        personService.addPerson(newPerson);
        User newuser = new User(id, jTextNickname.getText(), jPasswordUser.getText(), activeRol(rolActive), newPerson);
        userService.addUser(newuser);
    }
    
    private boolean confirmData(){
        if(jTextFirstName.getText().equals("First name") || jTextFirstName.getText().length()==0
                && jTextFirtsLastName.getText().length()==0 || jTextFirtsLastName.getText().equals("Firts lastname")
                && jTextEmail.getText().length()==0 || jTextEmail.getText().equals("user@domain.com")
                && jTextNickname.getText().length()==0 || jTextNickname.getText().equals("Nickname")){
            JOptionPane.showMessageDialog(null, "Tienes campos vacios en el registro.");
            return false;
        }
        else{
            if(jPasswordConfirmPassword.getText().length()==0
                    || jPasswordUser.getText().length()==0){
                JOptionPane.showMessageDialog(null, "las contraseñas estan vacias.");
                return false;
            }
            else if(!jPasswordConfirmPassword.getText().equals(jPasswordUser.getText())){
                JOptionPane.showMessageDialog(null, "las contraseñas no coincide.");
                return false;
            }
            else if(jPasswordConfirmPassword.getText().contains(" ")||
                    jPasswordUser.getText().contains(" ")){
                JOptionPane.showMessageDialog(null, "Las contraseñas no pueden contener espacios.");
                return false;
            }
            else{
                return true;
            }
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabelIMG = new javax.swing.JLabel();
        jLabelRegistry = new javax.swing.JLabel();
        jLabelRegistry1 = new javax.swing.JLabel();
        jLabelRegistry2 = new javax.swing.JLabel();
        jLabelRegistry3 = new javax.swing.JLabel();
        jLabelRegistry4 = new javax.swing.JLabel();
        jLabelRegistry5 = new javax.swing.JLabel();
        jLabelRegistry6 = new javax.swing.JLabel();
        jLabelRegistry7 = new javax.swing.JLabel();
        jLabelRegistry8 = new javax.swing.JLabel();
        jTextFirstName = new javax.swing.JTextField();
        jTextFirtsLastName = new javax.swing.JTextField();
        jTextSecondName = new javax.swing.JTextField();
        jTextSecondLastName = new javax.swing.JTextField();
        jTextEmail = new javax.swing.JTextField();
        jTextNickname = new javax.swing.JTextField();
        jButtonCreateUser = new javax.swing.JButton();
        jPasswordUser = new javax.swing.JPasswordField();
        jPasswordConfirmPassword = new javax.swing.JPasswordField();
        jButtonReturnLogin = new javax.swing.JButton();
        jLabelRegistry9 = new javax.swing.JLabel();
        jTArtis = new javax.swing.JToggleButton();

        jRadioButton1.setText("jRadioButton1");

        setPreferredSize(new java.awt.Dimension(680, 479));

        jLabelRegistry.setFont(new java.awt.Font("Noto Sans CJK SC", 1, 18)); // NOI18N
        jLabelRegistry.setText("Register for good music");

        jLabelRegistry1.setFont(new java.awt.Font("Noto Sans CJK SC", 1, 14)); // NOI18N
        jLabelRegistry1.setText("First name");

        jLabelRegistry2.setFont(new java.awt.Font("Noto Sans CJK SC", 1, 14)); // NOI18N
        jLabelRegistry2.setText("Second name");

        jLabelRegistry3.setFont(new java.awt.Font("Noto Sans CJK SC", 1, 14)); // NOI18N
        jLabelRegistry3.setText("Second lastname");

        jLabelRegistry4.setFont(new java.awt.Font("Noto Sans CJK SC", 1, 14)); // NOI18N
        jLabelRegistry4.setText("Firts lastname");

        jLabelRegistry5.setFont(new java.awt.Font("Noto Sans CJK SC", 1, 14)); // NOI18N
        jLabelRegistry5.setText("Password");

        jLabelRegistry6.setFont(new java.awt.Font("Noto Sans CJK SC", 1, 14)); // NOI18N
        jLabelRegistry6.setText("Email");

        jLabelRegistry7.setFont(new java.awt.Font("Noto Sans CJK SC", 1, 14)); // NOI18N
        jLabelRegistry7.setText("User - Nickname");

        jLabelRegistry8.setFont(new java.awt.Font("Noto Sans CJK SC", 1, 14)); // NOI18N
        jLabelRegistry8.setText("Confirm password");

        jTextFirstName.setText("First name");
        jTextFirstName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFirstNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFirstNameFocusLost(evt);
            }
        });
        jTextFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFirstNameActionPerformed(evt);
            }
        });

        jTextFirtsLastName.setText("Firts lastname");
        jTextFirtsLastName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFirtsLastNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFirtsLastNameFocusLost(evt);
            }
        });

        jTextSecondName.setText("Second name");
        jTextSecondName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextSecondNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextSecondNameFocusLost(evt);
            }
        });

        jTextSecondLastName.setText("Second lastname");
        jTextSecondLastName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextSecondLastNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextSecondLastNameFocusLost(evt);
            }
        });

        jTextEmail.setText("user@domain.com");
        jTextEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextEmailFocusLost(evt);
            }
        });

        jTextNickname.setText("Nickname");
        jTextNickname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextNicknameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextNicknameFocusLost(evt);
            }
        });

        jButtonCreateUser.setBackground(new java.awt.Color(0, 153, 0));
        jButtonCreateUser.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCreateUser.setText("Create account");
        jButtonCreateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateUserActionPerformed(evt);
            }
        });

        jPasswordUser.setText("password");
        jPasswordUser.setEchoChar('\u0000');
        jPasswordUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordUserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordUserFocusLost(evt);
            }
        });

        jPasswordConfirmPassword.setText("confirm password");
        jPasswordConfirmPassword.setEchoChar('\u0000');
        jPasswordConfirmPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordConfirmPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordConfirmPasswordFocusLost(evt);
            }
        });

        jButtonReturnLogin.setBackground(new java.awt.Color(255, 51, 51));
        jButtonReturnLogin.setForeground(new java.awt.Color(255, 255, 255));
        jButtonReturnLogin.setText("Cancel");
        jButtonReturnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReturnLoginActionPerformed(evt);
            }
        });

        jLabelRegistry9.setFont(new java.awt.Font("Noto Sans CJK SC", 1, 14)); // NOI18N
        jLabelRegistry9.setText("Are you artis?");

        jTArtis.setText("Yes");
        jTArtis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTArtisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabelRegistry)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelRegistry7)
                    .addComponent(jLabelRegistry6)
                    .addComponent(jTextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextNickname, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelRegistry1)
                                .addComponent(jLabelRegistry4)
                                .addComponent(jLabelRegistry5)
                                .addComponent(jTextFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFirtsLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(60, 60, 60)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextSecondName, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelRegistry8)
                                .addComponent(jLabelRegistry3)
                                .addComponent(jLabelRegistry2)
                                .addComponent(jTextSecondLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelRegistry9)
                                .addComponent(jTArtis)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPasswordUser, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonCreateUser))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButtonReturnLogin)
                                .addComponent(jPasswordConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 295, Short.MAX_VALUE)
                .addComponent(jLabelIMG)
                .addGap(50, 50, 50))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelRegistry, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRegistry1)
                    .addComponent(jLabelRegistry2))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextSecondName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelRegistry4)
                            .addComponent(jLabelRegistry3))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFirtsLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextSecondLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabelRegistry6)
                        .addGap(8, 8, 8)
                        .addComponent(jTextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelRegistry7)
                            .addComponent(jLabelRegistry9))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextNickname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTArtis))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelRegistry5)
                            .addComponent(jLabelRegistry8)))
                    .addComponent(jLabelIMG))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCreateUser)
                    .addComponent(jButtonReturnLogin))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCreateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateUserActionPerformed
        if(confirmData()){
            newUserRegistry();
            JOptionPane.showMessageDialog(null, "Registro Exitoso");
        }
        else{
            JOptionPane.showMessageDialog(null, "no se hizo el registro");
        }
    }//GEN-LAST:event_jButtonCreateUserActionPerformed

    private void jButtonReturnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReturnLoginActionPerformed
        
        JPLoginOfIndex loginPanel = new JPLoginOfIndex(this.index);
        Index changePanel = (Index) SwingUtilities.getWindowAncestor(this);
        changePanel.changeContentNewRegistry(loginPanel);
    }//GEN-LAST:event_jButtonReturnLoginActionPerformed

    private void jTextFirstNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFirstNameFocusGained
        if(jTextFirstName.getText().equals("First name")){
            jTextFirstName.setText(null);
            jTextFirstName.requestFocus();
            index.removePlaceHolderStyle(jTextFirstName);
        }
    }//GEN-LAST:event_jTextFirstNameFocusGained

    private void jTextFirstNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFirstNameFocusLost
        if(jTextFirstName.getText().length()==0){
            index.addPlaceHolderStyle(jTextFirstName);
            jTextFirstName.setText("First name");
        }
    }//GEN-LAST:event_jTextFirstNameFocusLost

    private void jTextSecondNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextSecondNameFocusGained
        if(jTextSecondName.getText().equals("Second name")){
            jTextSecondName.setText(null);
            jTextSecondName.requestFocus();
            index.removePlaceHolderStyle(jTextSecondName);
        }
    }//GEN-LAST:event_jTextSecondNameFocusGained

    private void jTextSecondNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextSecondNameFocusLost
        if(jTextSecondName.getText().length()==0){
            jTextSecondName.setText("Second name");
            index.addPlaceHolderStyle(jTextSecondName);
        }
    }//GEN-LAST:event_jTextSecondNameFocusLost

    private void jTextFirtsLastNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFirtsLastNameFocusGained
        if(jTextFirtsLastName.getText().equals("Firts lastname")){
            jTextFirtsLastName.setText(null);
            jTextFirtsLastName.requestFocus();
            index.removePlaceHolderStyle(jTextFirtsLastName);
        }
    }//GEN-LAST:event_jTextFirtsLastNameFocusGained

    private void jTextFirtsLastNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFirtsLastNameFocusLost
        if(jTextFirtsLastName.getText().length()==0){
            jTextFirtsLastName.setText("Firts lastname");
            index.addPlaceHolderStyle(jTextFirtsLastName);
        }
    }//GEN-LAST:event_jTextFirtsLastNameFocusLost

    private void jTextSecondLastNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextSecondLastNameFocusGained
        if(jTextSecondLastName.getText().equals("Second lastname")){
            jTextSecondLastName.setText(null);
            jTextSecondLastName.requestFocus();
            index.removePlaceHolderStyle(jTextSecondLastName);
        }
    }//GEN-LAST:event_jTextSecondLastNameFocusGained

    private void jTextSecondLastNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextSecondLastNameFocusLost
        if(jTextSecondLastName.getText().length()==0){
            jTextSecondLastName.setText("Second lastname");
            index.addPlaceHolderStyle(jTextSecondLastName);
        }
    }//GEN-LAST:event_jTextSecondLastNameFocusLost

    private void jTextEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextEmailFocusGained
        if(jTextEmail.getText().equals("user@domain.com")){
            jTextEmail.setText(null);
            jTextEmail.requestFocus();
            index.removePlaceHolderStyle(jTextEmail);
        }
    }//GEN-LAST:event_jTextEmailFocusGained

    private void jTextEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextEmailFocusLost
        if(jTextEmail.getText().length()==0){
            jTextEmail.setText("user@domain.com");
            index.addPlaceHolderStyle(jTextEmail);
        }
    }//GEN-LAST:event_jTextEmailFocusLost

    private void jTextNicknameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextNicknameFocusGained
        if(jTextNickname.getText().equals("Nickname")){
            jTextNickname.setText(null);
            jTextNickname.requestFocus();
            index.removePlaceHolderStyle(jTextNickname);
        }
    }//GEN-LAST:event_jTextNicknameFocusGained

    private void jTextNicknameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextNicknameFocusLost
        if(jTextNickname.getText().length()==0){
            jTextNickname.setText("Nickname");
            index.addPlaceHolderStyle(jTextNickname);
        }
    }//GEN-LAST:event_jTextNicknameFocusLost

    private void jPasswordUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordUserFocusGained
        if(jPasswordUser.getText().equals("password")){
            jPasswordUser.setText(null);
            jPasswordUser.requestFocus();
            jPasswordUser.setEchoChar('o');
            index.removePlaceHolderStyle(jPasswordUser);
        }
    }//GEN-LAST:event_jPasswordUserFocusGained

    private void jPasswordUserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordUserFocusLost
        if(jPasswordUser.getText().length()==0){
            jPasswordUser.setText("password");
            jPasswordUser.setEchoChar('\u0000');
            index.addPlaceHolderStyle(jPasswordUser);
        }
    }//GEN-LAST:event_jPasswordUserFocusLost

    private void jPasswordConfirmPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordConfirmPasswordFocusGained
        if(jPasswordConfirmPassword.getText().equals("confirm password")){
            jPasswordConfirmPassword.setText(null);
            jPasswordConfirmPassword.requestFocus();
            jPasswordConfirmPassword.setEchoChar('o');
            index.removePlaceHolderStyle(jPasswordConfirmPassword);
        }
    }//GEN-LAST:event_jPasswordConfirmPasswordFocusGained

    private void jPasswordConfirmPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordConfirmPasswordFocusLost
        if(jPasswordConfirmPassword.getText().length()==0){
            jPasswordConfirmPassword.setText("confirm password");
            jPasswordConfirmPassword.setEchoChar('\u0000');
            index.addPlaceHolderStyle(jPasswordConfirmPassword);
        }
    }//GEN-LAST:event_jPasswordConfirmPasswordFocusLost

    private void jTextFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFirstNameActionPerformed

    private void jTArtisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTArtisActionPerformed
        if(jTArtis.isSelected()){
            rolActive = true;
        }
        else{
            rolActive = false;
        }
    }//GEN-LAST:event_jTArtisActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCreateUser;
    private javax.swing.JButton jButtonReturnLogin;
    private javax.swing.JLabel jLabelIMG;
    private javax.swing.JLabel jLabelRegistry;
    private javax.swing.JLabel jLabelRegistry1;
    private javax.swing.JLabel jLabelRegistry2;
    private javax.swing.JLabel jLabelRegistry3;
    private javax.swing.JLabel jLabelRegistry4;
    private javax.swing.JLabel jLabelRegistry5;
    private javax.swing.JLabel jLabelRegistry6;
    private javax.swing.JLabel jLabelRegistry7;
    private javax.swing.JLabel jLabelRegistry8;
    private javax.swing.JLabel jLabelRegistry9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordConfirmPassword;
    private javax.swing.JPasswordField jPasswordUser;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JToggleButton jTArtis;
    private javax.swing.JTextField jTextEmail;
    private javax.swing.JTextField jTextFirstName;
    private javax.swing.JTextField jTextFirtsLastName;
    private javax.swing.JTextField jTextNickname;
    private javax.swing.JTextField jTextSecondLastName;
    private javax.swing.JTextField jTextSecondName;
    // End of variables declaration//GEN-END:variables
}
